name: HalfSlab
main: halfslab.HalfSlab
version: 1.1.4
description: HalfSlab - You can break half slab
authors: [DimoN]
website: http://playcraft.com.ua/

commands:
    halfslab:
        aliases: [hs]

permissions:
    halfslab.admin.reload:
        default: op
    halfslab.player.breakhalf:
        default: op
    halfslab.player.placesmoth:
        default: op
    halfslab.player.toslab:
        default: op
    halfslab.player.comparetoblock:
        default: op
    
