name: HalfSlab
main: halfslab.HalfSlab
version: 1.0.1
description: HalfSlab - You can break half slab
authors: [DimoN]
website: http://playcraft.com.ua/

commands:
    halfslab:
        aliases: [hs]

permissions:
    halfslab.admin.reload:
        default: op
    halfslab.player.break:
        default: op
