name: HalfSlab
main: halfslab.HalfSlab
version: 1.0
authors: [DimoN]
website: http://playcraft.com.ua/

commands:
    halfslab:
        aliases: [hs]

permissions:
    halfslab.admin.reload:
        default: op
    halfslab.player.break:
        default: op
